### PR TITLE
WZ from Carlos

### PR DESCRIPTION
**Pull request by vischia**

### CODE REVIEW

**Comment by vischia** [comment]
@cericeci , what is exactly included in your PR, apart from your commits?

**Comment by vischia** [comment]
I mean in your branch, the PR I did it to myself :dancer:

**Comment by cericeci** [comment]
It seems that my lack of expertise in git made me clone initially from CERN-PH-CMG instead of ECOP (before merging your own wz80x branch on top), thus creating this horrible mesh of commits. I guess that it shouldn't be a big deal for the work in this specific analysis but better be safe than sorry.... I'll rebase everything properly to our beloved ECOP

**Comment by vischia** [comment]
Carlos,
habiendote basado en ECOP, también basaste el CMGTools non-lite en ECOP?

**Pull request merged**
